// Generated by Haxe 3.4.0
(function ($hx_exports, $global) { "use strict";
$hx_exports["bridge"] = $hx_exports["bridge"] || {};
$hx_exports["bridge"]["js"] = $hx_exports["bridge"]["js"] || {};
$hx_exports["bridge"]["js"]["PeoteSocketBridge"] = $hx_exports["bridge"]["js"]["PeoteSocketBridge"] || {};
var $estr = function() { return js_Boot.__string_rec(this,''); };
function $extend(from, fields) {
	function Inherit() {} Inherit.prototype = from; var proto = new Inherit();
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var HxOverrides = function() { };
HxOverrides.__name__ = true;
HxOverrides.cca = function(s,index) {
	var x = s.charCodeAt(index);
	if(x != x) {
		return undefined;
	}
	return x;
};
Math.__name__ = true;
var Std = function() { };
Std.__name__ = true;
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
var bridge_js_PeoteSocketBridge = $hx_exports["PeoteSocketBridge"] = function() { };
bridge_js_PeoteSocketBridge.__name__ = true;
bridge_js_PeoteSocketBridge.main = function() {
};
bridge_js_PeoteSocketBridge.load = function(param) {
	bridge_js_PeoteSocketBridge.proxys = param.proxys;
	bridge_js_PeoteSocketBridge.onload = param.onload;
	bridge_js_PeoteSocketBridge.onfail = param.onfail;
	if(param.prefareWebsockets) {
		bridge_js_PeoteSocketBridge.loadWS();
	} else {
		bridge_js_PeoteSocketBridge.loadSWF();
	}
};
bridge_js_PeoteSocketBridge.loadSWF = function() {
	if(bridge_js_PeoteSocketBridge.checkedSWF) {
		return;
	}
	bridge_js_PeoteSocketBridge.checkedSWF = true;
	console.log("SWFObject.version:" + swfobject.version);
	console.log("FlashPlayerVersion:" + Std.string(swfobject.getFlashPlayerVersion()));
	if(swfobject.hasFlashPlayerVersion("11.2.0")) {
		swfobject.addDomLoadEvent(function() {
			var div = window.document.createElement("div");
			window.document.body.appendChild(div);
			var id = div.id = "PeoteSocketBridge";
			var params = { "flashvars" : "onloadcallback=bridge.js.PeoteSocketBridge.peoteSocketBridgeAvailable", "menu" : "false", "scale" : "noScale", "allowScriptAccess" : "always", "allowNetworking" : "true", "bgcolor" : "#000000"};
			if(bridge_js_PeoteSocketBridge.proxys.proxyServerSWF != null) {
				params.flashvars += "&proxyserver=" + bridge_js_PeoteSocketBridge.proxys.proxyServerSWF;
			}
			if(bridge_js_PeoteSocketBridge.proxys.proxyPortSWF != null) {
				params.flashvars += "&proxyport=" + bridge_js_PeoteSocketBridge.proxys.proxyPortSWF;
			}
			swfobject.createSWF({ data : "peoteSocketBridge.swf", width : "1", height : "1"},params,id).style.position = "absolute";
			console.log("try to embed peoteSocketBridge...");
			var timer = new haxe_Timer(6000);
			timer.run = function() {
				timer.stop();
				if(!bridge_js_PeoteSocketBridge.swfBridgeReady) {
					swfobject.removeSWF(id);
					console.log("could not load peoteSocketBridge.swf");
					bridge_js_PeoteSocketBridge.loadWS();
				}
			};
		});
	} else {
		console.log("no flashplayer found, using websocket instead");
		bridge_js_PeoteSocketBridge.loadWS();
	}
};
bridge_js_PeoteSocketBridge.loadWS = function() {
	if(bridge_js_PeoteSocketBridge.checkedWS) {
		return;
	}
	bridge_js_PeoteSocketBridge.checkedWS = true;
	console.log("check for websocket support");
	var supported = ('WebSocket' in window || 'MozWebSocket' in window);
	if(supported) {
		console.log("Websockets available");
		bridge_js_PeoteSocketBridge.onload();
	} else {
		bridge_js_PeoteSocketBridge.loadSWF();
	}
};
bridge_js_PeoteSocketBridge.peoteSocketBridgeAvailable = $hx_exports["bridge"]["js"]["PeoteSocketBridge"]["peoteSocketBridgeAvailable"] = function() {
	bridge_js_PeoteSocketBridge.swfBridgeReady = true;
	console.log("swf-bridge is READY");
	bridge_js_PeoteSocketBridge.onload();
};
var de_peote_io_PeoteBytesInput = $hx_exports["PeoteBytesInput"] = function(bytes) {
	if(bytes != null) {
		this.bytesInput = new haxe_io_BytesInput(bytes);
	} else {
		this.bytesInput = new haxe_io_BytesInput(new haxe_io_Bytes(new ArrayBuffer(0)));
	}
};
de_peote_io_PeoteBytesInput.__name__ = true;
de_peote_io_PeoteBytesInput.main = function() {
};
de_peote_io_PeoteBytesInput.prototype = {
	bytesLeft: function() {
		return this.bytesInput.totlen - this.bytesInput.pos;
	}
	,append: function(b,max_pos_before_trim) {
		if(max_pos_before_trim == null) {
			max_pos_before_trim = 0;
		}
		var bytes = new haxe_io_Bytes(new ArrayBuffer(this.bytesInput.totlen - this.bytesInput.pos + b.length));
		if(this.bytesInput.totlen - this.bytesInput.pos > 0) {
			bytes.blit(0,this.bytesInput.readAll(),0,this.bytesInput.totlen - this.bytesInput.pos);
		}
		bytes.blit(this.bytesInput.totlen - this.bytesInput.pos,b,0,b.length);
		this.bytesInput = new haxe_io_BytesInput(bytes);
	}
	,get_length: function() {
		return this.bytesInput.totlen;
	}
	,get_position: function() {
		return this.bytesInput.pos;
	}
	,set_position: function(p) {
		return this.bytesInput.set_position(p);
	}
	,readByte: function() {
		return this.bytesInput.readByte();
	}
	,readUInt16: function() {
		return this.bytesInput.readUInt16();
	}
	,readInt16: function() {
		return this.bytesInput.readInt16();
	}
	,readInt32: function() {
		return this.bytesInput.readInt32();
	}
	,readFloat: function() {
		return this.bytesInput.readFloat();
	}
	,readDouble: function() {
		return this.bytesInput.readDouble();
	}
	,readString: function() {
		var len = this.bytesInput.readUInt16();
		return this.bytesInput.readString(len);
	}
	,__class__: de_peote_io_PeoteBytesInput
};
var haxe_io_Output = function() { };
haxe_io_Output.__name__ = true;
haxe_io_Output.prototype = {
	writeByte: function(c) {
		throw new js__$Boot_HaxeError("Not implemented");
	}
	,writeBytes: function(s,pos,len) {
		if(pos < 0 || len < 0 || pos + len > s.length) {
			throw new js__$Boot_HaxeError(haxe_io_Error.OutsideBounds);
		}
		var b = s.b;
		var k = len;
		while(k > 0) {
			this.writeByte(b[pos]);
			++pos;
			--k;
		}
		return len;
	}
	,writeFullBytes: function(s,pos,len) {
		while(len > 0) {
			var k = this.writeBytes(s,pos,len);
			pos += k;
			len -= k;
		}
	}
	,writeUInt16: function(x) {
		if(x < 0 || x >= 65536) {
			throw new js__$Boot_HaxeError(haxe_io_Error.Overflow);
		}
		if(this.bigEndian) {
			this.writeByte(x >> 8);
			this.writeByte(x & 255);
		} else {
			this.writeByte(x & 255);
			this.writeByte(x >> 8);
		}
	}
	,writeString: function(s) {
		var b = haxe_io_Bytes.ofString(s);
		this.writeFullBytes(b,0,b.length);
	}
	,__class__: haxe_io_Output
};
var haxe_io_BytesOutput = function() {
	this.b = new haxe_io_BytesBuffer();
};
haxe_io_BytesOutput.__name__ = true;
haxe_io_BytesOutput.__super__ = haxe_io_Output;
haxe_io_BytesOutput.prototype = $extend(haxe_io_Output.prototype,{
	writeByte: function(c) {
		this.b.b.push(c);
	}
	,writeBytes: function(buf,pos,len) {
		var _this = this.b;
		if(pos < 0 || len < 0 || pos + len > buf.length) {
			throw new js__$Boot_HaxeError(haxe_io_Error.OutsideBounds);
		}
		var b2 = buf.b;
		var _g1 = pos;
		var _g = pos + len;
		while(_g1 < _g) _this.b.push(b2[_g1++]);
		return len;
	}
	,getBytes: function() {
		return this.b.getBytes();
	}
	,__class__: haxe_io_BytesOutput
});
var de_peote_io_PeoteBytesOutput = $hx_exports["PeoteBytesOutput"] = function() {
	haxe_io_BytesOutput.call(this);
};
de_peote_io_PeoteBytesOutput.__name__ = true;
de_peote_io_PeoteBytesOutput.main = function() {
};
de_peote_io_PeoteBytesOutput.__super__ = haxe_io_BytesOutput;
de_peote_io_PeoteBytesOutput.prototype = $extend(haxe_io_BytesOutput.prototype,{
	writeString: function(s) {
		this.writeUInt16(haxe_io_Bytes.ofString(s).length);
		haxe_io_BytesOutput.prototype.writeString.call(this,s);
	}
	,__class__: de_peote_io_PeoteBytesOutput
});
var de_peote_socket_PeoteSocketTool = $hx_exports["PeoteSocketTool"] = function() { };
de_peote_socket_PeoteSocketTool.__name__ = true;
de_peote_socket_PeoteSocketTool.toBytes = function(arr) {
	return haxe_io_Bytes.ofData(new Uint8Array(arr).buffer);
};
de_peote_socket_PeoteSocketTool.fromBytes = function(bytes) {
	var _g = [];
	var _g2 = 0;
	var _g1 = bytes.length;
	while(_g2 < _g1) _g.push(bytes.b[_g2++]);
	return _g;
};
var de_peote_socket_PeoteSocket = $hx_exports["PeoteSocket"] = function(callbacks) {
	this.is_proxy = false;
	console.log("new PeoteWebSocket (" + Std.string(callbacks) + ")");
	this.cb = callbacks;
};
de_peote_socket_PeoteSocket.__name__ = true;
de_peote_socket_PeoteSocket.main = function() {
};
de_peote_socket_PeoteSocket.prototype = {
	connect: function(server,port) {
		var _server = server;
		var _port = port;
		if(bridge_js_PeoteSocketBridge.proxys != null) {
			if(bridge_js_PeoteSocketBridge.proxys.proxyServerWS != null) {
				_server = bridge_js_PeoteSocketBridge.proxys.proxyServerWS;
			}
			if(bridge_js_PeoteSocketBridge.proxys.proxyPortWS != null) {
				_port = bridge_js_PeoteSocketBridge.proxys.proxyPortWS;
			}
		}
		this.ws = new WebSocket("ws://" + _server + ":" + _port);
		this.ws.binaryType = "arraybuffer";
		this.ws.onopen = $bind(this,this.onOpen);
		this.ws.onclose = $bind(this,this.onClose);
		this.ws.onerror = $bind(this,this.onError);
		this.ws.onmessage = $bind(this,this.onMessage);
		if(_server != server || _port != port) {
			this.is_proxy = true;
			this.forward_server = server;
			this.forward_port = port;
		}
	}
	,close: function() {
		this.ws.close();
	}
	,writeByte: function(b) {
		this.ws.send(new Uint8Array([b]),{ binary : true, mask : false});
	}
	,writeBytes: function(data) {
		this.ws.send(new Uint8Array(data.b.bufferValue),{ binary : true, mask : false});
	}
	,flush: function() {
	}
	,onOpen: function() {
		if(this.is_proxy) {
			var output = new de_peote_io_PeoteBytesOutput();
			output.writeString(this.forward_server);
			output.writeUInt16(this.forward_port);
			this.writeBytes(output.getBytes());
		}
		this.cb.onConnect(true,"connect");
	}
	,onClose: function() {
		this.cb.onClose("closed");
	}
	,onError: function(s) {
		this.cb.onError(s);
	}
	,onMessage: function(e) {
		var tmp = this.cb;
		var tmp1 = haxe_io_Bytes.ofData(e.data);
		tmp.onData(tmp1);
	}
	,__class__: de_peote_socket_PeoteSocket
};
var haxe_Timer = function(time_ms) {
	var me = this;
	this.id = setInterval(function() {
		me.run();
	},time_ms);
};
haxe_Timer.__name__ = true;
haxe_Timer.prototype = {
	stop: function() {
		if(this.id == null) {
			return;
		}
		clearInterval(this.id);
		this.id = null;
	}
	,run: function() {
	}
	,__class__: haxe_Timer
};
var haxe_io_Bytes = function(data) {
	this.length = data.byteLength;
	this.b = new Uint8Array(data);
	this.b.bufferValue = data;
	data.hxBytes = this;
	data.bytes = this.b;
};
haxe_io_Bytes.__name__ = true;
haxe_io_Bytes.ofString = function(s) {
	var a = [];
	var i = 0;
	while(i < s.length) {
		var c = s.charCodeAt(i++);
		if(55296 <= c && c <= 56319) {
			c = c - 55232 << 10 | s.charCodeAt(i++) & 1023;
		}
		if(c <= 127) {
			a.push(c);
		} else if(c <= 2047) {
			a.push(192 | c >> 6);
			a.push(128 | c & 63);
		} else if(c <= 65535) {
			a.push(224 | c >> 12);
			a.push(128 | c >> 6 & 63);
			a.push(128 | c & 63);
		} else {
			a.push(240 | c >> 18);
			a.push(128 | c >> 12 & 63);
			a.push(128 | c >> 6 & 63);
			a.push(128 | c & 63);
		}
	}
	return new haxe_io_Bytes(new Uint8Array(a).buffer);
};
haxe_io_Bytes.ofData = function(b) {
	var hb = b.hxBytes;
	if(hb != null) {
		return hb;
	}
	return new haxe_io_Bytes(b);
};
haxe_io_Bytes.prototype = {
	blit: function(pos,src,srcpos,len) {
		if(pos < 0 || srcpos < 0 || len < 0 || pos + len > this.length || srcpos + len > src.length) {
			throw new js__$Boot_HaxeError(haxe_io_Error.OutsideBounds);
		}
		if(srcpos == 0 && len == src.b.byteLength) {
			this.b.set(src.b,pos);
		} else {
			this.b.set(src.b.subarray(srcpos,srcpos + len),pos);
		}
	}
	,getString: function(pos,len) {
		if(pos < 0 || len < 0 || pos + len > this.length) {
			throw new js__$Boot_HaxeError(haxe_io_Error.OutsideBounds);
		}
		var s = "";
		var b = this.b;
		var fcc = String.fromCharCode;
		var i = pos;
		var max = pos + len;
		while(i < max) {
			var c = b[i++];
			if(c < 128) {
				if(c == 0) {
					break;
				}
				s += fcc(c);
			} else if(c < 224) {
				s += fcc((c & 63) << 6 | b[i++] & 127);
			} else if(c < 240) {
				s += fcc((c & 31) << 12 | (b[i++] & 127) << 6 | b[i++] & 127);
			} else {
				var u = (c & 15) << 18 | (b[i++] & 127) << 12 | (b[i++] & 127) << 6 | b[i++] & 127;
				s += fcc((u >> 10) + 55232);
				s += fcc(u & 1023 | 56320);
			}
		}
		return s;
	}
	,toString: function() {
		return this.getString(0,this.length);
	}
	,__class__: haxe_io_Bytes
};
var haxe_io_BytesBuffer = function() {
	this.b = [];
};
haxe_io_BytesBuffer.__name__ = true;
haxe_io_BytesBuffer.prototype = {
	getBytes: function() {
		var bytes = new haxe_io_Bytes(new Uint8Array(this.b).buffer);
		this.b = null;
		return bytes;
	}
	,__class__: haxe_io_BytesBuffer
};
var haxe_io_Input = function() { };
haxe_io_Input.__name__ = true;
haxe_io_Input.prototype = {
	readByte: function() {
		throw new js__$Boot_HaxeError("Not implemented");
	}
	,readBytes: function(s,pos,len) {
		var k = len;
		var b = s.b;
		if(pos < 0 || len < 0 || pos + len > s.length) {
			throw new js__$Boot_HaxeError(haxe_io_Error.OutsideBounds);
		}
		try {
			while(k > 0) {
				b[pos] = this.readByte();
				++pos;
				--k;
			}
		} catch( eof ) {
			if (eof instanceof js__$Boot_HaxeError) eof = eof.val;
			if( js_Boot.__instanceof(eof,haxe_io_Eof) ) {
			} else throw(eof);
		}
		return len - k;
	}
	,readAll: function(bufsize) {
		if(bufsize == null) {
			bufsize = 16384;
		}
		var buf = new haxe_io_Bytes(new ArrayBuffer(bufsize));
		var total = new haxe_io_BytesBuffer();
		try {
			while(true) {
				var len = this.readBytes(buf,0,bufsize);
				if(len == 0) {
					throw new js__$Boot_HaxeError(haxe_io_Error.Blocked);
				}
				if(len < 0 || len > buf.length) {
					throw new js__$Boot_HaxeError(haxe_io_Error.OutsideBounds);
				}
				var b2 = buf.b;
				var _g1 = 0;
				while(_g1 < len) total.b.push(b2[_g1++]);
			}
		} catch( e ) {
			if (e instanceof js__$Boot_HaxeError) e = e.val;
			if( js_Boot.__instanceof(e,haxe_io_Eof) ) {
			} else throw(e);
		}
		return total.getBytes();
	}
	,readFullBytes: function(s,pos,len) {
		while(len > 0) {
			var k = this.readBytes(s,pos,len);
			if(k == 0) {
				throw new js__$Boot_HaxeError(haxe_io_Error.Blocked);
			}
			pos += k;
			len -= k;
		}
	}
	,readFloat: function() {
		return haxe_io_FPHelper.i32ToFloat(this.readInt32());
	}
	,readDouble: function() {
		var i1 = this.readInt32();
		var i2 = this.readInt32();
		if(this.bigEndian) {
			return haxe_io_FPHelper.i64ToDouble(i2,i1);
		} else {
			return haxe_io_FPHelper.i64ToDouble(i1,i2);
		}
	}
	,readInt16: function() {
		var ch1 = this.readByte();
		var ch2 = this.readByte();
		var n = this.bigEndian ? ch2 | ch1 << 8 : ch1 | ch2 << 8;
		if((n & 32768) != 0) {
			return n - 65536;
		}
		return n;
	}
	,readUInt16: function() {
		var ch1 = this.readByte();
		var ch2 = this.readByte();
		if(this.bigEndian) {
			return ch2 | ch1 << 8;
		} else {
			return ch1 | ch2 << 8;
		}
	}
	,readInt32: function() {
		var ch1 = this.readByte();
		var ch2 = this.readByte();
		var ch3 = this.readByte();
		var ch4 = this.readByte();
		if(this.bigEndian) {
			return ch4 | ch3 << 8 | ch2 << 16 | ch1 << 24;
		} else {
			return ch1 | ch2 << 8 | ch3 << 16 | ch4 << 24;
		}
	}
	,readString: function(len) {
		var b = new haxe_io_Bytes(new ArrayBuffer(len));
		this.readFullBytes(b,0,len);
		return b.toString();
	}
	,__class__: haxe_io_Input
};
var haxe_io_BytesInput = function(b,pos,len) {
	if(pos == null) {
		pos = 0;
	}
	if(len == null) {
		len = b.length - pos;
	}
	if(pos < 0 || len < 0 || pos + len > b.length) {
		throw new js__$Boot_HaxeError(haxe_io_Error.OutsideBounds);
	}
	this.b = b.b;
	this.pos = pos;
	this.len = len;
	this.totlen = len;
};
haxe_io_BytesInput.__name__ = true;
haxe_io_BytesInput.__super__ = haxe_io_Input;
haxe_io_BytesInput.prototype = $extend(haxe_io_Input.prototype,{
	set_position: function(p) {
		if(p < 0) {
			p = 0;
		} else if(p > this.totlen) {
			p = this.totlen;
		}
		this.len = this.totlen - p;
		return this.pos = p;
	}
	,readByte: function() {
		if(this.len == 0) {
			throw new js__$Boot_HaxeError(new haxe_io_Eof());
		}
		this.len--;
		return this.b[this.pos++];
	}
	,readBytes: function(buf,pos,len) {
		if(pos < 0 || len < 0 || pos + len > buf.length) {
			throw new js__$Boot_HaxeError(haxe_io_Error.OutsideBounds);
		}
		if(this.len == 0 && len > 0) {
			throw new js__$Boot_HaxeError(new haxe_io_Eof());
		}
		if(this.len < len) {
			len = this.len;
		}
		var b1 = this.b;
		var b2 = buf.b;
		var _g1 = 0;
		var _g = len;
		while(_g1 < _g) {
			var i = _g1++;
			b2[pos + i] = b1[this.pos + i];
		}
		this.pos += len;
		this.len -= len;
		return len;
	}
	,__class__: haxe_io_BytesInput
});
var haxe_io_Eof = function() {
};
haxe_io_Eof.__name__ = true;
haxe_io_Eof.prototype = {
	toString: function() {
		return "Eof";
	}
	,__class__: haxe_io_Eof
};
var haxe_io_Error = { __ename__ : true, __constructs__ : ["Blocked","Overflow","OutsideBounds","Custom"] };
haxe_io_Error.Blocked = ["Blocked",0];
haxe_io_Error.Blocked.toString = $estr;
haxe_io_Error.Blocked.__enum__ = haxe_io_Error;
haxe_io_Error.Overflow = ["Overflow",1];
haxe_io_Error.Overflow.toString = $estr;
haxe_io_Error.Overflow.__enum__ = haxe_io_Error;
haxe_io_Error.OutsideBounds = ["OutsideBounds",2];
haxe_io_Error.OutsideBounds.toString = $estr;
haxe_io_Error.OutsideBounds.__enum__ = haxe_io_Error;
haxe_io_Error.Custom = function(e) { var $x = ["Custom",3,e]; $x.__enum__ = haxe_io_Error; $x.toString = $estr; return $x; };
var haxe_io_FPHelper = function() { };
haxe_io_FPHelper.__name__ = true;
haxe_io_FPHelper.i32ToFloat = function(i) {
	var exp = i >>> 23 & 255;
	var sig = i & 8388607;
	if(sig == 0 && exp == 0) {
		return 0.0;
	}
	return (1 - (i >>> 31 << 1)) * (1 + Math.pow(2,-23) * sig) * Math.pow(2,exp - 127);
};
haxe_io_FPHelper.i64ToDouble = function(low,high) {
	var exp = (high >> 20 & 2047) - 1023;
	var sig = (high & 1048575) * 4294967296. + (low >>> 31) * 2147483648. + (low & 2147483647);
	if(sig == 0 && exp == -1023) {
		return 0.0;
	}
	return (1 - (high >>> 31 << 1)) * (1.0 + Math.pow(2,-52) * sig) * Math.pow(2,exp);
};
var js__$Boot_HaxeError = function(val) {
	Error.call(this);
	this.val = val;
	this.message = String(val);
	if(Error.captureStackTrace) {
		Error.captureStackTrace(this,js__$Boot_HaxeError);
	}
};
js__$Boot_HaxeError.__name__ = true;
js__$Boot_HaxeError.wrap = function(val) {
	if((val instanceof Error)) {
		return val;
	} else {
		return new js__$Boot_HaxeError(val);
	}
};
js__$Boot_HaxeError.__super__ = Error;
js__$Boot_HaxeError.prototype = $extend(Error.prototype,{
	__class__: js__$Boot_HaxeError
});
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.getClass = function(o) {
	if((o instanceof Array) && o.__enum__ == null) {
		return Array;
	} else {
		var cl = o.__class__;
		if(cl != null) {
			return cl;
		}
		var name = js_Boot.__nativeClassName(o);
		if(name != null) {
			return js_Boot.__resolveNativeClass(name);
		}
		return null;
	}
};
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(o instanceof Array) {
			if(o.__enum__) {
				if(o.length == 2) {
					return o[0];
				}
				var str = o[0] + "(";
				s += "\t";
				var _g1 = 2;
				var _g = o.length;
				while(_g1 < _g) {
					var i = _g1++;
					if(i != 2) {
						str += "," + js_Boot.__string_rec(o[i],s);
					} else {
						str += js_Boot.__string_rec(o[i],s);
					}
				}
				return str + ")";
			}
			var l = o.length;
			var i1;
			var str1 = "[";
			s += "\t";
			var _g11 = 0;
			var _g2 = l;
			while(_g11 < _g2) {
				var i2 = _g11++;
				str1 += (i2 > 0 ? "," : "") + js_Boot.__string_rec(o[i2],s);
			}
			str1 += "]";
			return str1;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( e ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var k = null;
		var str2 = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		for( var k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str2.length != 2) {
			str2 += ", \n";
		}
		str2 += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str2 += "\n" + s + "}";
		return str2;
	case "string":
		return o;
	default:
		return String(o);
	}
};
js_Boot.__interfLoop = function(cc,cl) {
	if(cc == null) {
		return false;
	}
	if(cc == cl) {
		return true;
	}
	var intf = cc.__interfaces__;
	if(intf != null) {
		var _g1 = 0;
		var _g = intf.length;
		while(_g1 < _g) {
			var i = intf[_g1++];
			if(i == cl || js_Boot.__interfLoop(i,cl)) {
				return true;
			}
		}
	}
	return js_Boot.__interfLoop(cc.__super__,cl);
};
js_Boot.__instanceof = function(o,cl) {
	if(cl == null) {
		return false;
	}
	switch(cl) {
	case Array:
		if((o instanceof Array)) {
			return o.__enum__ == null;
		} else {
			return false;
		}
		break;
	case Bool:
		return typeof(o) == "boolean";
	case Dynamic:
		return true;
	case Float:
		return typeof(o) == "number";
	case Int:
		if(typeof(o) == "number") {
			return (o|0) === o;
		} else {
			return false;
		}
		break;
	case String:
		return typeof(o) == "string";
	default:
		if(o != null) {
			if(typeof(cl) == "function") {
				if(o instanceof cl) {
					return true;
				}
				if(js_Boot.__interfLoop(js_Boot.getClass(o),cl)) {
					return true;
				}
			} else if(typeof(cl) == "object" && js_Boot.__isNativeObj(cl)) {
				if(o instanceof cl) {
					return true;
				}
			}
		} else {
			return false;
		}
		if(cl == Class ? o.__name__ != null : false) {
			return true;
		}
		if(cl == Enum ? o.__ename__ != null : false) {
			return true;
		}
		return o.__enum__ == cl;
	}
};
js_Boot.__nativeClassName = function(o) {
	var name = js_Boot.__toStr.call(o).slice(8,-1);
	if(name == "Object" || name == "Function" || name == "Math" || name == "JSON") {
		return null;
	}
	return name;
};
js_Boot.__isNativeObj = function(o) {
	return js_Boot.__nativeClassName(o) != null;
};
js_Boot.__resolveNativeClass = function(name) {
	return $global[name];
};
var js_html_compat_ArrayBuffer = function(a) {
	if((a instanceof Array) && a.__enum__ == null) {
		this.a = a;
		this.byteLength = a.length;
	} else {
		var len = a;
		this.a = [];
		var _g1 = 0;
		var _g = len;
		while(_g1 < _g) this.a[_g1++] = 0;
		this.byteLength = len;
	}
};
js_html_compat_ArrayBuffer.__name__ = true;
js_html_compat_ArrayBuffer.sliceImpl = function(begin,end) {
	var u = new Uint8Array(this,begin,end == null ? null : end - begin);
	var result = new ArrayBuffer(u.byteLength);
	new Uint8Array(result).set(u);
	return result;
};
js_html_compat_ArrayBuffer.prototype = {
	slice: function(begin,end) {
		return new js_html_compat_ArrayBuffer(this.a.slice(begin,end));
	}
	,__class__: js_html_compat_ArrayBuffer
};
var js_html_compat_Uint8Array = function() { };
js_html_compat_Uint8Array.__name__ = true;
js_html_compat_Uint8Array._new = function(arg1,offset,length) {
	var arr;
	if(typeof(arg1) == "number") {
		arr = [];
		var _g1 = 0;
		var _g = arg1;
		while(_g1 < _g) {
			var i = _g1++;
			arr[i] = 0;
		}
		arr.byteLength = arr.length;
		arr.byteOffset = 0;
		arr.buffer = new js_html_compat_ArrayBuffer(arr);
	} else if(js_Boot.__instanceof(arg1,js_html_compat_ArrayBuffer)) {
		var buffer = arg1;
		if(offset == null) {
			offset = 0;
		}
		if(length == null) {
			length = buffer.byteLength - offset;
		}
		if(offset == 0) {
			arr = buffer.a;
		} else {
			arr = buffer.a.slice(offset,offset + length);
		}
		arr.byteLength = arr.length;
		arr.byteOffset = offset;
		arr.buffer = buffer;
	} else if((arg1 instanceof Array) && arg1.__enum__ == null) {
		arr = arg1.slice();
		arr.byteLength = arr.length;
		arr.byteOffset = 0;
		arr.buffer = new js_html_compat_ArrayBuffer(arr);
	} else {
		throw new js__$Boot_HaxeError("TODO " + Std.string(arg1));
	}
	arr.subarray = js_html_compat_Uint8Array._subarray;
	arr.set = js_html_compat_Uint8Array._set;
	return arr;
};
js_html_compat_Uint8Array._set = function(arg,offset) {
	if(js_Boot.__instanceof(arg.buffer,js_html_compat_ArrayBuffer)) {
		var a = arg;
		if(arg.byteLength + offset > this.byteLength) {
			throw new js__$Boot_HaxeError("set() outside of range");
		}
		var _g1 = 0;
		var _g = arg.byteLength;
		while(_g1 < _g) {
			var i = _g1++;
			this[i + offset] = a[i];
		}
	} else if((arg instanceof Array) && arg.__enum__ == null) {
		var a1 = arg;
		if(a1.length + offset > this.byteLength) {
			throw new js__$Boot_HaxeError("set() outside of range");
		}
		var _g11 = 0;
		var _g2 = a1.length;
		while(_g11 < _g2) {
			var i1 = _g11++;
			this[i1 + offset] = a1[i1];
		}
	} else {
		throw new js__$Boot_HaxeError("TODO");
	}
};
js_html_compat_Uint8Array._subarray = function(start,end) {
	var a = js_html_compat_Uint8Array._new(this.slice(start,end));
	a.byteOffset = start;
	return a;
};
var $_, $fid = 0;
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $fid++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = function(){ return f.method.apply(f.scope, arguments); }; f.scope = o; f.method = m; o.hx__closures__[m.__id__] = f; } return f; }
String.prototype.__class__ = String;
String.__name__ = true;
Array.__name__ = true;
var Int = { __name__ : ["Int"]};
var Dynamic = { __name__ : ["Dynamic"]};
var Float = Number;
Float.__name__ = ["Float"];
var Bool = Boolean;
Bool.__ename__ = ["Bool"];
var Class = { __name__ : ["Class"]};
var Enum = { };
Object.defineProperty(de_peote_io_PeoteBytesInput.prototype,"length",{ get : de_peote_io_PeoteBytesInput.prototype.get_length});
Object.defineProperty(de_peote_io_PeoteBytesInput.prototype,"position",{ get : de_peote_io_PeoteBytesInput.prototype.get_position, set : de_peote_io_PeoteBytesInput.prototype.set_position});
var ArrayBuffer = $global.ArrayBuffer || js_html_compat_ArrayBuffer;
if(ArrayBuffer.prototype.slice == null) {
	ArrayBuffer.prototype.slice = js_html_compat_ArrayBuffer.sliceImpl;
}
var Uint8Array = $global.Uint8Array || js_html_compat_Uint8Array._new;
bridge_js_PeoteSocketBridge.checkedSWF = false;
bridge_js_PeoteSocketBridge.checkedWS = false;
bridge_js_PeoteSocketBridge.swfBridgeReady = false;
js_Boot.__toStr = ({ }).toString;
js_html_compat_Uint8Array.BYTES_PER_ELEMENT = 1;
de_peote_socket_PeoteSocket.main();
})(typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this, typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);
